### ISSUE TITLE
Add ROS parameters

### ISSUE THREAD

**Issue by mstoelzle** [tud-cor-sr/ros2-elastica#12]
Please think about which parameters should be initialized as ROS parameters and put into a launch file.

For now, I am mainly thinking of the timer frequency, which is currently hard-coded: https://github.com/tud-cor-sr/ros2-elastica/blob/testing_versions/elastica_sim_control/elastica_sim_control/elastica_publisher_subscriber.py#L89

**Comment by RUFFY-369** [comment]
Hi @mstoelzle , I've added the ROS params the recent commits.

**Comment by mstoelzle** [comment]
Please also add the timer period for the callback (e.g. the period for publishing state updates). You might also want to decide to call it `pub_freq` (e.g. publication frequency in the unit Hz - this is how most people usually think about it)

**Comment by RUFFY-369** [comment]
Oh! Yeah sure that was the remaining one along with buffer size. 
Usually people say it triggers for every half second so, may be frequency would be better to use here for dev clarity purpose.

**Comment by RUFFY-369** [comment]
Hi @mstoelzle , I've solved the issue in the recent commits, please review
