### ISSUE TITLE
Slight formatting improvements for README

### ISSUE THREAD

**Issue by mstoelzle** [tud-cor-sr/ros2-elastica#13]
A small formatting suggestion for the README:

- The title of the repository should be formatted with a heading one (e.g. # Title)
- The sections of the README should be formatted with a heading two (e.g. ## Section Heading)
- Everything else and subsections should be formatted with a heading three (e.g. ### Subsection)
- Also your code-snippets someshave an empty line at the end. That looks a bit weird

**Comment by RUFFY-369** [comment]
Hi @mstoelzle , I have done the mentioned improvements in the recent commits.

**Comment by mstoelzle** [comment]
Looks good
