### ISSUE TITLE
Replace print statements with ROS logger 

### ISSUE THREAD

**Issue by mstoelzle** [tud-cor-sr/ros2-elastica#14]
Please replace all print statements with ros logger messages (either info, warning, error or debug):
```
self.get_logger().info("Your message")
```

**Comment by RUFFY-369** [comment]
Yeah sure, thanks for pointing out.
That would be a better way to get the status of the running node

**Comment by RUFFY-369** [comment]
Hi @mstoelzle , I've replaced them in the recent commits
