### ISSUE TITLE
Publish orientation of all nodes

### ISSUE THREAD

**Issue by mstoelzle** [tud-cor-sr/ros2-elastica#20]
Please do not just publish the orientation of the tip, but of all nodes:
https://github.com/tud-cor-sr/ros2-elastica/blob/main/elastica_sim_control/elastica_sim_control/continuum_flagella_ros2.py#L178

This will be relevant feedback for our controllers

**Comment by RUFFY-369** [comment]
Yeah sure, thanks for mentioning this out. The orientation of all the elements would be necessary for the controllers to perform efficient grasping or other tasks

**Comment by RUFFY-369** [comment]
Hi @mstoelzle , in the new model, I'm publishing the orientaiton of all elements in each segment.
