### ISSUE TITLE
Rename elastica_sim_control to elastica_sim

### ISSUE THREAD

**Issue by mstoelzle** [tud-cor-sr/ros2-elastica#21]
Please rename the package `elastica_sim_control` to `elastica_sim` as it should only handle the simulation. The controller will be placed in a different package (but in the same repo).

**Comment by RUFFY-369** [comment]
Sure, will make the changes in the upcoming pushes for the packages' names

**Comment by RUFFY-369** [comment]
Hi @mstoelzle , changed in the recent commits.
