### ISSUE TITLE
Rename rod_tip_orientation to orientation

### ISSUE THREAD

**Issue by mstoelzle** [tud-cor-sr/ros2-elastica#22]
Please rename `rod_tip_orientation_X` to `orientation_XX`. You can add a code comment that you always refer to the orientation of the tip of the rod:

https://github.com/tud-cor-sr/ros2-elastica/blob/main/elastica_sim/elastica_sim/continuum_flagella_ros2.py#L42
https://github.com/tud-cor-sr/ros2-elastica/blob/main/elastica_sim/elastica_sim/continuum_flagella_ros2.py#L187

This is more in line with the common nomenclature

**Comment by RUFFY-369** [comment]
Hi @mstoelzle , thanks for enhancing the namings, I've pushed the required commits regarding the same
