### ISSUE TITLE
Bug calling uniformtorques_mag_cal in continuum_flagella_ros2.py

### ISSUE THREAD

**Issue by mstoelzle** [tud-cor-sr/ros2-elastica#24]
I think I found a bug in the `continuum_flagella_ros2.py` file:
https://github.com/tud-cor-sr/ros2-elastica/blob/main/elastica_sim/elastica_sim/continuum_flagella_ros2.py#L150
I nowhere see an implementation of the function `uniformtorques_mag_cal`. I think in the snake simulator, you commented this line.

**Comment by RUFFY-369** [comment]
Hi @mstoelzle , I commented it in flagella as well in the recent commits as I'm not publishing it. 'Cause the control torques  given the controller node are already being published.
