### ISSUE TITLE
Integrate into our Dockerfile

### ISSUE THREAD

**Issue by mstoelzle** [tud-cor-sr/ros2-elastica#5]
Please integrate the simulator into our Dockerfile: https://github.com/tud-cor-sr/sr-ros2-bundles

The repo can be added to the `overlay.repo` file so that it is automatically downloaded. You can develop in your own branch and then create a PR at the end.

**Important:** The elastica dependencies and the repo should only be included in the Docker image, if an argument is set to true in `docker-compose`. E.g. we should also be able to build docker images easily without the Elastica simulator

**Comment by RUFFY-369** [comment]
HI @mstoelzle , I have pushed the required commits to [https://github.com/tud-cor-sr/sr-ros2-bundles](https://github.com/tud-cor-sr/sr-ros2-bundles)

**Comment by RUFFY-369** [comment]
Hi @mstoelzle , Should we close this issue now?

**Comment by mstoelzle** [comment]
Please update the README now to reflect that we are now referring to our sr-ros2-bundles repo instead of our prebuilt Docker image

**Comment by RUFFY-369** [comment]
Hi @mstoelzle , I have updated the readme in the recent push. Please check it.
